"""
models/priority_assessment.py

Represents the final priority assigned to an area.

Generated by:
    PriorityAgent

Used by:
    AllocationAgent
    DecisionAgent
    Dashboard
"""

from dataclasses import dataclass


@dataclass(slots=True)
class PriorityAssessment:
    """
    Final priority assessment for an area.

    This object does NOT contain weather or hospital data.
    It only stores the prioritization result.
    """

    # --------------------------------------------------
    # Area Information
    # --------------------------------------------------

    area_id: str

    area_name: str

    # --------------------------------------------------
    # Priority
    # --------------------------------------------------

    priority_score: float

    priority_level: str

    # --------------------------------------------------
    # Explanation
    # --------------------------------------------------

    reason: str

    # --------------------------------------------------
    # Recommendation
    # --------------------------------------------------

    recommended_action: str